# This is a basic workflow to help you get started with Actions

name: Run Snake Game Turtle Version

# Controls when the action will run. 
on:
  # Triggers the workflow on schedule based on cron time
  schedule:
    - cron: "* * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
#       # Runs a single command using the runners shell
#       - name: Run the python file to start the game
#         run: python -s snake_using_turtle.py
        
      - name: Test with pytest 1
        run: |
          pip install pytest
          pytest test.py --doctest-modules --junitxml=junit/test-results.xml
  test2:
    runs-on: ubuntu-latest
    steps:    
      - name: Test with pytest 2
        run: |
          pip install pytest
          pytest test2.py --doctest-modules --junitxml=junit/test2-results.xml
